kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java:8
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: sample
  Project: fis7-camel-springboot
  Name: fis7-camel-springboot
